[deploy]
bucket = 'cfn-artifacts-tayo'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = '*'
EnvBackendUrl = '*'
DDBMessageTable = 'CrdDdb-DynamoDBTable-12SD1WASIUCT8'